services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: stock_data
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d stock_data"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-webserver:
    image: apache/airflow:2.7.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/stock_data
      AIRFLOW__CORE__FERNET_KEY: "uN2w2x0uXg9SgQh8yA4dZ1Vb4kUrcfLAvyN4Y9UPyGQ="
      AIRFLOW__WEBSERVER__SECRET_KEY: "uN2w2x0uXg9SgQh8yA4dZ1Vb4kUrcfLAvyN4Y9UPyGQ"
      ALPHA_VANTAGE_API_KEY: "WC7KHWA0IAV5PAMT"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "
        pip install -r /requirements.txt &&
        airflow db init &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password 'admin' --force || true &&
        airflow webserver
      "
    ports:
      - "8080:8080"

  airflow-scheduler:
    image: apache/airflow:2.7.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/stock_data
      AIRFLOW__CORE__FERNET_KEY: "uN2w2x0uXg9SgQh8yA4dZ1Vb4kUrcfLAvyN4Y9UPyGQ="
      AIRFLOW__WEBSERVER__SECRET_KEY: "uN2w2x0uXg9SgQh8yA4dZ1Vb4kUrcfLAvyN4Y9UPyGQ"
      ALPHA_VANTAGE_API_KEY: "WC7KHWA0IAV5PAMT"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "
        pip install -r /requirements.txt &&
        airflow scheduler
      "

volumes:
  postgres_data:
